"""Generate the indicator twin of a strategy .pine file.

Lines between `// <strategy>` and `// </strategy>` (markers included) are dropped, and lines starting with
`// <indicator> ` are uncommented. Everything else is shared, so the indicator shows the same setups, table and
alerts as the strategy, without orders.
Usage: python tools/pine_twin.py pine/orb_alt.pine pine/orb_alt_indicator.pine
"""
import re
import sys


def twin(src):
    out, skip = [], False
    for line in src.splitlines():
        tag = line.strip()
        if tag == "// <strategy>":
            skip = True
            continue
        if tag == "// </strategy>":
            skip = False
            continue
        if skip:
            continue
        m = re.match(r"^(\s*)// <indicator> (.*)$", line)
        out.append(m.group(1) + m.group(2) if m else line)
    if skip:
        raise ValueError("unclosed // <strategy> block")
    text = "\n".join(out) + "\n"
    if "strategy." in text.replace("strategy.long", "").replace("strategy.short", ""):
        raise ValueError("strategy.* call outside a // <strategy> block")
    return text.replace("is generated from this file by tools/pine_twin.py: edit this file only.",
                        "is generated by tools/pine_twin.py from pine/orb_alt.pine: do not edit.")


if __name__ == "__main__":
    src, dst = sys.argv[1:3]
    open(dst, "w", newline="\n").write(twin(open(src).read()))
    print("wrote", dst)
